version: "3.9"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: local_pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: sa@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - local_pgadmin:/var/lib/pgadmin

volumes:
  local_pgdata:
  local_pgadmin:
